import type { BranchenPageData } from './branchen-data'

// Englische Inhalte der Branchenseiten. Struktur identisch zu branchen-data.ts.
export const BRANCHEN_DATA_EN: Record<string, BranchenPageData> = {
  hotel: {
    slug: 'hotel',
    metaTitle: '360° tour for hotels – more direct bookings',
    metaDescription: 'More direct bookings, fewer OTA commissions: professional 360° tours for hotels from CHF 3\'490. Swiss provider – the VR tour is yours, no subscription.',
    badge: 'Hotels & resorts',
    headline: '360° tour for your hotel',
    tagline: 'More direct bookings, less OTA dependency. Show guests your rooms, spa, restaurant and lobby – before they book.',
    heroImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1900&q=80&auto=format&fit=crop',
    challenges: [
      { title: 'OTA costs eat the margin', description: 'CHF 30\'000–100\'000 per year for hotels. 15–18% commission per booking to Booking.com & co.' },
      { title: '“So much nicer than in the photos!”', description: '90% of guests say this. But online? Only static photos that fail to convey the atmosphere.' },
      { title: 'Guests book back on Booking', description: 'Your website shows static photos, the guest is unsure and books back on the OTA – 15–18% commission.' },
    ],
    stats: [
      { value: '+48%', label: 'more direct bookings' },
      { value: '130%', label: 'higher booking probability (18–34-year-olds)' },
      { value: '3×', label: 'longer dwell time on your website' },
      { value: '2×', label: 'more Google profile views' },
    ],
    statsNote: 'Sources: Google Street View business data, Matterport Insights, hospitality industry studies',
    sources: [
      { label: 'Omni Hotels study: 67% higher booking probability with a 360° tour (EXP360)', url: 'https://exp360.com/blog/how-hotels-use-vr-360-images-and-videos-to-increase-bookings/' },
      { label: 'Visiting Media: how virtual tours increase hotel bookings', url: 'https://visitingmedia.com/5-ways-virtual-tours-help-hotels-increase-bookings/' },
      { label: 'ScienceDirect: AR/VR in hotels – effect on guest satisfaction and booking intent', url: 'https://www.sciencedirect.com/science/article/pii/S0278431923002050' },
    ],
    captures: ['Room types (single, double, suite)', 'Lobby & reception', 'Restaurant', 'Spa & wellness', 'Event spaces', 'Outdoor areas'],
    comparisonTitle: 'Hotel with vs without Signature Tour',
    comparisonKicker: 'The difference',
    comparisonWithoutHead: 'Without a 360° tour',
    comparisonWithoutSub: 'photos on the website only',
    comparisonRows: [
      { label: 'Dwell time', without: '1–2 minutes, then the guest clicks away', with: '5–8 minutes inside the experience' },
      { label: 'Direct bookings', without: 'Guest books back on Booking & co.', with: '+48% more direct bookings' },
      { label: 'Guest trust', without: 'Low – static photos only', with: 'High – rooms & spa experienced in advance' },
      { label: 'OTA commissions', without: '15–18% per booking', with: 'Noticeably reduced' },
      { label: 'Google visibility', without: 'Standard listing', with: 'Preferred placement with tour' },
      { label: 'Image quality', without: 'Phone snapshots', with: 'Professional shots, clean floor (nadir)' },
    ],
    roiTitle: 'Just 10 direct bookings pay for your VR tour',
    roiSteps: [
      { label: 'Average room rate', value: 'CHF 200 / night' },
      { label: 'Saved OTA commission (18%)', value: 'CHF 36 / night' },
      { label: '10 direct bookings of 2 nights', value: 'CHF 720 saved' },
    ],
    roiResult: 'The VR tour often pays for itself within the first quarter.',
    packageName: 'Hotel package',
    packagePrice: 'from CHF 3\'490.–',
    packageFeatures: [
      'All room types, lobby, restaurant, spa, outdoor areas',
      'Booking-link hotspots & floor-plan navigation',
      'Multilingualism (DE / FR / EN)',
      'Google Business integration',
      'Incl. 12 months of Signature Evolution (care service)',
      'Large properties, thermal baths & resorts: Pro line from CHF 4\'497.–',
    ],
    faqs: [
      { question: 'How long does the shoot take?', answer: '4–6 hours depending on hotel size. We schedule the appointment after check-out / before check-in.' },
      { question: 'What if we renovate rooms?', answer: 'Depending on the service package, panorama updates are already included – or individually from CHF 180.– per scene. No completely new shoot needed.' },
      { question: 'Can the VR tour link into our booking system?', answer: 'Yes. Guests can book the room type they are currently viewing directly from within the virtual tour.' },
      { question: 'Does the VR tour also work on smartphones?', answer: 'Yes, fully responsive. No app needed. VR headsets are supported as well.' },
    ],
  },

  restaurant: {
    slug: 'restaurant',
    metaTitle: '360° tour for restaurants',
    metaDescription: '93% of guests google before choosing a restaurant. Show your ambience with a professional 360° tour.',
    badge: 'Gastronomy',
    headline: '360° tour for your restaurant',
    tagline: '93% of guests google before choosing a restaurant. Show your ambience – not just your menu.',
    heroImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1900&q=80&auto=format&fit=crop',
    challenges: [
      { title: 'Uncontrolled Google photos', description: 'Guests upload shaky, badly lit phone photos that shape the first impression.' },
      { title: 'Online invisibility', description: 'Without visual content you lose in search results. The competition wins.' },
      { title: '14-hour days = no marketing', description: 'No time for professional content creation alongside daily operations.' },
    ],
    stats: [
      { value: '+85%', label: 'more reservations through virtual tours' },
      { value: '+50%', label: 'more website visits' },
      { value: '2×', label: 'more Google Maps views' },
      { value: '93%', label: 'google before choosing a restaurant' },
    ],
    statsNote: 'Sources: Google Street View business data, gastronomy industry studies',
    sources: [
      { label: 'Google/Ipsos “Impact of Search Listings”: listings with a virtual tour generate twice as much interest (CloudPano)', url: 'https://www.cloudpano.com/blog/how-google-street-view-tours-increase-foot-traffic-to-local-businesses' },
      { label: 'Panoee: how Google Street View increases foot traffic', url: 'https://panoee.com/why-google-street-view-can-boost-traffic-to-your-store/' },
    ],
    captures: ['Dining room', 'Terrace & outdoor areas', 'Bar & lounge', 'Private rooms & events', 'Kitchen (optional) – shows transparency, builds trust'],
    roiTitle: 'Less than an espresso per day',
    roiSteps: [
      { label: 'Investment (gastro package)', value: 'from CHF 2\'890.– one-time' },
      { label: 'Calculated over 3 years', value: 'around CHF 2.65 / day' },
      { label: '1 extra reservation per week (CHF 45 p.p.)', value: '> CHF 7\'000 / year' },
    ],
    roiResult: 'Just two extra reservations per week pay for the entire tour.',
    extraSection: {
      title: 'Google Business integration',
      description: 'Your 360° tour is embedded directly in your Google Business Profile. Professional shots replace uncontrolled guest photos.',
      items: [
        'VR tour directly in the Google Business Profile',
        'Higher click-through rate on Google Maps',
        'More calls, more reservations',
        'Competitive advantage vs restaurants without a VR tour',
      ],
    },
    comparisonTitle: 'Restaurant with vs without Signature Tour',
    comparisonKicker: 'The difference',
    comparisonWithoutHead: 'Photos & menu only',
    comparisonRows: [
      { label: 'First impression online', without: 'Shaky guest photos on Google', with: 'A professional ambience you control' },
      { label: 'Reservations', without: 'Guest is unsure, keeps clicking', with: 'The ambience convinces before the reservation' },
      { label: 'Google Maps', without: 'Standard listing', with: 'VR tour in the profile – more clicks & calls' },
      { label: 'Effort', without: 'No marketing alongside daily operations', with: 'Created once, works for years' },
      { label: 'Freshness', without: 'Photos age', with: 'Seasonal updates possible' },
      { label: 'Image quality', without: 'Phone snapshots', with: 'Professional shots, clean floor (nadir)' },
    ],
    packageName: 'Gastro package',
    packagePrice: 'from CHF 2\'890.–',
    packageFeatures: [
      'Signature Tour with Google Business integration',
      'Day/night mode for daytime and evening ambience',
      'QR code pack for table and shop window',
      '1 seasonal update included (festive decoration, summer tables)',
      'Incl. 12 months of Signature Care (care service)',
      'Small venues: Basic Tour from CHF 990.–',
    ],
    faqs: [
      { question: 'Do we have to close during the shoot?', answer: 'No, we shoot before opening or during a quiet period. 60–90 minutes are usually enough.' },
      { question: 'Can we have the VR tour adapted seasonally?', answer: 'Yes, 1 seasonal update is included. Further updates can be added at any time.' },
      { question: 'What happens to our guests’ old Google photos?', answer: 'The professional tour appears prominently. Guest photos remain, but your VR tour dominates the visual first impression.' },
    ],
  },

  'spa-wellness': {
    slug: 'spa-wellness',
    metaTitle: '360° tour for spa & wellness',
    metaDescription: 'Make your feel-good atmosphere tangible online. Professional 360° tours for spa facilities.',
    badge: 'Spa & wellness',
    headline: 'Make your feel-good atmosphere tangible',
    tagline: 'Guests say: “It’s even more beautiful than in the pictures.” Let them feel the atmosphere already online.',
    heroImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1900&q=80&auto=format&fit=crop',
    demoTour: { url: 'https://vtour.cloud/e16tqj/ee82pes6/#node69', title: 'AQUAVIRAT – spa & baths', note: 'A real Signature Tour: pool, sauna landscape and relaxation areas – including booking directly inside the VR tour.' },
    challenges: [
      { title: 'Atmosphere is hard to convey', description: 'Photos show rooms, but not the feeling: sauna warmth, the silence of the relaxation areas, the scale of the facility.' },
      { title: 'A conversion gap', description: 'Visitors are interested but do not book. The decisive experience that builds trust is missing.' },
      { title: 'Competitive pressure', description: 'Large wellness chains invest in video marketing. Differentiation has to be authentic.' },
    ],
    stats: [
      { value: '+45%', label: 'more bookings after a virtual tour' },
      { value: '67%', label: 'higher booking probability among tour viewers' },
      { value: '4–5×', label: 'longer dwell time on pages with a 360° tour' },
      { value: '15–25%', label: 'adoption in the DACH region – your head start, now' },
    ],
    statsNote: 'Sources: Matterport Insights, wellness & hospitality industry studies',
    sources: [
      { label: 'EXP360: 360° content in hotels and wellness', url: 'https://exp360.com/blog/how-hotels-use-vr-360-images-and-videos-to-increase-bookings/' },
      { label: 'ScienceDirect: virtual tours and customer satisfaction – quasi-experiment (Airbnb)', url: 'https://www.sciencedirect.com/science/article/abs/pii/S1447677025000105' },
    ],
    captures: ['Sauna landscape', 'Treatment rooms', 'Relaxation areas', 'Pools & whirlpools', 'Outdoor areas', 'Garden / natural pool / panoramic view'],
    extraSection: {
      title: 'Privacy & discretion',
      description: 'Your guests remain protected. We guarantee absolute discretion at every shoot.',
      items: [
        'Shoot outside opening hours – no guests in the images',
        'GDPR-compliant: no people, no identifiable details',
        'Professional post-production with quality control',
        'You approve every image before publication',
        'Optional: exclude specific areas',
      ],
    },
    comparisonTitle: 'Spa with vs without Signature Tour',
    comparisonKicker: 'The difference',
    comparisonWithoutHead: 'Photos only',
    comparisonRows: [
      { label: 'Atmosphere', without: 'Photos show rooms, not the feeling', with: 'Calm & premium quality tangible' },
      { label: 'Bookings', without: 'Prospects hesitate', with: 'The experience builds trust → booking' },
      { label: 'Discretion', without: 'Uncontrolled guest photos', with: 'Shots without guests, approval in advance' },
      { label: 'Differentiation', without: 'Like everyone else', with: 'A visible edge over the chains' },
      { label: 'Google visibility', without: 'Standard listing', with: 'VR tour in the profile' },
      { label: 'Image quality', without: 'Snapshots', with: 'Professional shots, clean floor (nadir)' },
    ],
    packageName: 'Spa & wellness premium tour',
    packagePrice: 'from CHF 3\'490.–',
    packageFeatures: [
      'Signature Tour of the entire spa facility',
      'Audio guide & day/night mode for tangible atmosphere',
      'Shoot outside opening hours, GDPR-compliant',
      'Google Business integration & website embedding',
      'Incl. 12 months of Signature Care (care service)',
      'Optional: four-seasons terrace – CHF 1\'490.– / year',
    ],
    faqs: [
      { question: 'How do you make sure no guests appear in the images?', answer: 'Exclusive shooting outside operating hours in a pre-agreed time window. The spa area is closed to guests.' },
      { question: 'Can we exclude specific areas?', answer: 'Yes, you decide what is shown. Technical rooms, staff zones etc. can be left out.' },
      { question: 'How long does the shoot take for a complete spa facility?', answer: '2–4 hours depending on size. Larger facilities with indoor and outdoor areas may take half a day. Delivery in 5–7 days.' },
    ],
  },

  fitnessstudio: {
    slug: 'fitnessstudio',
    metaTitle: '360° tour for fitness studios',
    metaDescription: 'Lower the entry barrier for first-time visitors. 130% higher visit probability with a 360° tour.',
    badge: 'Fitness & sport',
    headline: 'Experience your gym – before the first step is taken',
    tagline: '82% research online. Lower the entry barrier for first-time visitors.',
    heroImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1900&q=80&auto=format&fit=crop',
    challenges: [
      { title: '“You have to experience it”', description: 'Quality cannot be judged without a visit. High entry barrier for first-time visitors.' },
      { title: '20% annual churn', description: 'The industry struggles with high churn. Members who know what to expect stay longer.' },
      { title: 'Discount chains dominate', description: 'McFit, FitX dominate search with big marketing budgets. Differentiate online as a quality gym.' },
    ],
    stats: [
      { value: '130%', label: 'higher visit probability with a Google listing with tour' },
      { value: '2×', label: 'more Google Maps views vs listings without a VR tour' },
      { value: 'EUR 960', label: 'average lifetime value per member (24 months × €40)' },
    ],
    statsNote: 'Sources: Google Street View business data, fitness industry studies',
    sources: [
      { label: 'Google/Ipsos “Impact of Search Listings”: twice as much interest with a virtual tour (CloudPano)', url: 'https://www.cloudpano.com/blog/how-google-street-view-tours-increase-foot-traffic-to-local-businesses' },
      { label: 'TeliportMe: virtual tour software market analysis 2024', url: 'https://teliportme.com/blog/a-deep-dive-into-the-virtual-tour-software-market/' },
    ],
    captures: ['Training floor', 'Free weights area', 'Cardio area', 'Class room(s)', 'Wellness & sauna (if available)', 'Changing rooms & showers'],
    extraSection: {
      title: 'Quality over price',
      description: 'Discount chains win on price – win on quality. But only if it is visible online.',
      items: [
        'High-quality equipment vs mass processing',
        'Personal atmosphere vs anonymous operation',
        'Clean, modern changing rooms',
        'Class rooms, wellness areas and extras justify the premium price',
        'The “I want to train here” feeling before the trial workout',
      ],
    },
    roiTitle: '3 new members pay for your VR tour',
    roiSteps: [
      { label: 'Value per member (24 mo. × CHF 40)', value: 'around CHF 960' },
      { label: 'Investment (fitness package)', value: 'from CHF 2\'890.– one-time' },
      { label: 'Break-even', value: '3 new members' },
    ],
    roiResult: 'Works for 3 years – with no recurring advertising costs and no scatter loss.',
    comparisonTitle: 'Gym with vs without Signature Tour',
    comparisonKicker: 'The difference',
    comparisonWithoutHead: 'Photos only',
    comparisonRows: [
      { label: 'Entry barrier', without: 'First-time visitor unsure, does not come', with: 'Gym experienced in advance → trial workout' },
      { label: 'Differentiation', without: 'Lost against the discounters', with: 'Quality made visible' },
      { label: 'Member retention', without: 'Wrong expectations, quick cancellation', with: 'Those who know what to expect stay longer' },
      { label: 'Google Maps', without: 'Standard listing', with: 'VR tour in the profile – more views' },
      { label: 'Social media', without: 'No shareable content', with: 'Shareable link for Instagram & co.' },
      { label: 'Image quality', without: 'Snapshots', with: 'Professional shots, clean floor (nadir)' },
    ],
    packageName: 'Fitness package',
    packagePrice: 'from CHF 2\'890.–',
    packageFeatures: [
      'Signature Tour of the entire gym',
      'Lead capture form (“request a trial workout”)',
      'Google Business integration & website embedding',
      'Optimised for mobile, desktop, TV and VR headsets',
      'Incl. 12 months of Signature Care (care service)',
      'Delivery in 5–7 working days',
    ],
    faqs: [
      { question: 'Are members shown during the shoot?', answer: 'No, we shoot outside peak hours or before opening. The gym is shown empty and tidy – it always looks best that way.' },
      { question: 'Our gym is not particularly large. Is it still worth it?', answer: 'Yes. Compact, well-equipped gyms look impressive in 360°. The spatial effect comes fully into its own.' },
      { question: 'Can we use the VR tour for social media?', answer: 'Yes, a shareable link for Instagram, Facebook, newsletters and review portals. No app download needed.' },
    ],
  },

  immobilien: {
    slug: 'immobilien',
    metaTitle: 'Professional 360° tours for real estate',
    metaDescription: 'Fewer wasted viewings, better-qualified prospects. 360° tours without a long-term contract.',
    badge: 'Real estate & agents',
    headline: 'Professional 360° tours for your properties',
    tagline: 'Fewer wasted viewings, better-qualified prospects. Without a long-term contract.',
    heroImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1900&q=80&auto=format&fit=crop',
    demoTour: { url: 'https://vtour.cloud/e16tqj/cltkwbjc/', title: 'Luxury Apartment – Widen', note: 'A real Signature Tour of a premium apartment: living spaces, kitchen, bathroom and outdoor areas open for viewing around the clock.' },
    challenges: [
      { title: 'Viewing tourism', description: 'Driving across town, unlocking, presenting. After 5 minutes the prospect says: “Not what I expected.”' },
      { title: 'Competition from the big agencies', description: 'Engel & Völkers already use virtual tours and visualisations. Without a comparable presence you lose mandates.' },
      { title: 'Owner expectations', description: 'Owners expect professional marketing. Just standard photos? Then the mandate goes to the agent with the better concept.' },
    ],
    stats: [
      { value: '+40%', label: 'more clicks on listings with a virtual tour' },
      { value: '+95%', label: 'higher contact rate on listings with a 360° tour' },
      { value: '5×', label: 'faster sale through pre-qualified prospects' },
      { value: '3×', label: 'longer dwell time on the listing' },
    ],
    statsNote: 'Sources: Matterport Insights, National Association of Realtors (NAR)',
    sources: [
      { label: 'Matterport study: buyers and sellers overwhelmingly prefer listings with 3D tours', url: 'https://matterport.com/news/new-study-shows-property-buyers-and-sellers-overwhelmingly-prefer-listings-3d-tours' },
      { label: 'Matterport: properties with 3D tours sell up to 31% faster', url: 'https://matterport.com/blog/3d-tours-properties-sell-31-faster-and-higher-price' },
      { label: 'NAR: Home Buyers & Sellers Generational Trends Report', url: 'https://www.nar.realtor/research-and-statistics/research-reports/home-buyer-and-seller-generational-trends' },
    ],
    captures: ['Living spaces', 'Kitchen', 'Bathrooms', 'Outdoor areas', 'Floor plan integration (optional)'],
    comparisonTitle: 'Why agents switch to Signatour',
    comparisonKicker: 'The honest comparison',
    comparisonWithoutHead: 'Usual providers',
    comparisonWithoutSub: 'Ogulo, Matterport',
    comparisonRows: [
      { label: 'Price per property', without: 'Recurring monthly fee + setup, runs forever', with: 'from CHF 1\'623.– per property (10-tour card) – then it is yours' },
      { label: 'Contract commitment', without: '12–24 months minimum term', with: 'None – multi-tour card with no expiry date' },
      { label: 'Your effort', without: 'Scan yourself, learn the software (DIY)', with: 'Zero – we come, shoot, deliver' },
      { label: 'Image quality', without: 'Depends on your own photos', with: 'Professional photographer, clean floor (nadir 95–100%)' },
      { label: 'Google & portals', without: 'Not included', with: 'Google Business, Homegate & ImmoScout included' },
      { label: 'Data sovereignty', without: 'Provider cloud, cancellation = data loss', with: 'With you – no vendor lock-in' },
    ],
    extraSection: {
      title: 'Portal compatibility',
      description: 'Our 360° tours work on all major real estate portals.',
      items: [
        'Homegate – virtual tour directly in the listing',
        'ImmoScout24.ch – maximum visibility through tour integration',
        'flatfox – modern presentation for digital tenant search',
        'newhome – professional presence on the Swiss marketplace',
        'Your own website – simple embedding via iFrame or link',
      ],
    },
    roiTitle: 'One won mandate pays for the whole card',
    roiSteps: [
      { label: 'VR tour per property (10-tour card)', value: 'CHF 1\'623.–' },
      { label: 'More clicks on listings', value: '+40%' },
      { label: 'Higher contact rate on listings', value: '+95%' },
    ],
    roiResult: 'A single won mandate pays for the complete card – for luxury properties the commission runs to five figures.',
    packageName: 'Signature multi-tour cards',
    packagePrice: 'CHF 2\'497.– per property',
    packageFeatures: [
      'Single property: CHF 2\'497.– per property',
      '5-tour card: CHF 9\'990.– (CHF 1\'998.– per property, approx. 20% benefit)',
      '10-tour card: CHF 16\'230.– (CHF 1\'623.– per property, 35% benefit)',
      'Every VR tour in Signature quality, fully in your corporate design',
      'Flexible use, no expiry date',
      'Google & portal integration per property',
      'Incl. 12 months of care service per tour',
    ],
    faqs: [
      { question: 'How quickly is the VR tour available after the shoot?', answer: 'Usually 5–10 working days. Urgent: express delivery in 3 working days (+30%).' },
      { question: 'What happens when the property is sold or rented?', answer: 'The VR tour is deactivated/deleted. Use the next tour on the card for a new property. No expiry date.' },
      { question: 'Does the property have to be empty for the shoot?', answer: 'No. Furnished properties often look more appealing in 360°. Easier to imagine living in. We advise on the optimal preparation.' },
    ],
  },

  'banken-versicherungen': {
    slug: 'banken-versicherungen',
    metaTitle: '360° tour for banks, insurances & law firms',
    metaDescription: 'Trust begins before the first appointment: discreet 360° tours for banks, insurances and law firms. Swiss provider, GDPR-compliant.',
    badge: 'Banks, insurances & law firms',
    headline: 'Trust is built before the first appointment is booked',
    tagline: 'In financial and legal services, the first impression decides the mandate enquiry. Show professionalism and discretion – before the first conversation takes place.',
    heroImage: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1900&q=80&auto=format&fit=crop',
    challenges: [
      { title: 'A high barrier before the first meeting', description: 'Anyone entrusting wealth, insurance or a legal case wants to know who they are dealing with. An anonymous website does not lower this barrier.' },
      { title: 'Interchangeable web presences', description: 'Stock photos and standard texts shape the industry. Showing your own premises proves substance where others merely claim it.' },
      { title: 'Premium rooms remain invisible', description: 'You invested in representative reception and consulting rooms – online, nobody sees them before the appointment.' },
    ],
    stats: [
      { value: '49%', label: 'of clients assess a law firm online before calling' },
      { value: '94%', label: 'higher perceived trustworthiness with a complete online presence' },
      { value: '2×', label: 'more interest in listings with a virtual tour' },
      { value: '24/7', label: 'your reception is digitally always open' },
    ],
    sources: [
      { label: 'Digital Roots Media: 49% assess the firm via the website before calling', url: 'https://www.digitalrootsmedia.com/blog/legal/law-firm-web-design-convert-visitors-clients/' },
      { label: 'Google/Ipsos “Impact of Search Listings”: 94% higher perceived credibility, 2× more interest with a virtual tour (CloudPano)', url: 'https://www.cloudpano.com/blog/how-google-street-view-tours-increase-foot-traffic-to-local-businesses' },
      { label: 'Panoee: the effect of Street View content on local businesses', url: 'https://panoee.com/why-google-street-view-can-boost-traffic-to-your-store/' },
    ],
    captures: ['Reception & lobby', 'Consulting rooms', 'Meeting rooms', 'Teller hall (banks)', 'Library & work areas (law firms)', 'Exterior & access'],
    extraSection: {
      title: 'Discretion & security',
      description: 'We know the requirements of sensitive industries – every shoot follows a clear approval process.',
      items: [
        'Shoot outside business hours – no clients, no employees in the image',
        'No documents, screens or security-relevant details in the shots',
        'You approve every panorama before publication',
        'Security-critical areas are excluded',
        'GDPR-compliant hosting in Switzerland/EU, data processing agreement included',
      ],
    },
    comparisonTitle: 'With vs without Signature Tour',
    comparisonKicker: 'The difference',
    comparisonWithoutHead: 'Website & stock photos only',
    comparisonRows: [
      { label: 'First impression', without: 'Anonymous stock photos', with: 'Your real premises – instant trust' },
      { label: 'Entry barrier', without: 'High before the first meeting', with: 'Lowered – the client knows you in advance' },
      { label: 'Discretion', without: 'No control', with: 'Without people/documents, approval process' },
      { label: 'Differentiation', without: 'Interchangeable presence', with: 'Visibly professional' },
      { label: 'Availability', without: 'Office hours only', with: 'Digital reception around the clock' },
      { label: 'Image quality', without: 'Stock material', with: 'Professional shots, clean floor (nadir)' },
    ],
    packageName: 'Branch tiers',
    packagePrice: 'from CHF 2\'497.– per location',
    packageFeatures: [
      '1 location: CHF 2\'497.–',
      '3–4 locations: CHF 2\'247.– per location (10%)',
      '5–9 locations: CHF 1\'873.– per location (25%)',
      'from 10 locations: CHF 1\'623.– per location (35%)',
      'Signature Tour in your corporate design, one contact for all locations',
      'Discreet approval process before publication',
      'Recommended with a service package per location',
    ],
    faqs: [
      { question: 'How do you ensure discretion?', answer: 'We shoot outside business hours, without people, documents or screen content. Every panorama goes through your approval process before it goes online. Security-critical areas stay out of scope.' },
      { question: 'How long does the shoot take?', answer: 'For reception, consulting and meeting rooms usually 1–2 hours – schedulable in the evening or at the weekend, without interrupting operations.' },
      { question: 'Is it worth it for a small law firm?', answer: 'Especially there: clients compare online before enquiring. The only firm in town that shows its premises stands out visibly – and the VR tour works for years without follow-up costs.' },
      { question: 'Is it also available in German or French?', answer: 'Yes. Consulting & projects in German, French and English – and the VR tour itself can be produced in multiple languages (from CHF 300 per additional language).' },
    ],
  },

  eventlocations: {
    slug: 'eventlocations',
    metaTitle: '360° tour for event venues & showrooms',
    metaDescription: 'Couples and event planners compare online: 360° tours for event venues, halls and showrooms. Fewer wasted viewings, more qualified enquiries.',
    badge: 'Event venues & showrooms',
    headline: 'Your venue convinces – before the enquiry even arrives',
    tagline: 'Couples, event planners and buyers compare online. Those who make hall, stage and ambience tangible receive the qualified enquiry – the competition only the next click.',
    heroImage: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=1900&q=80&auto=format&fit=crop',
    challenges: [
      { title: 'Every viewing costs hours', description: 'Coordinate the appointment, prepare the venue, run the viewing – and after 10 minutes the prospect realises the hall is too small.' },
      { title: 'Photos do not show spatial impact', description: 'Ceiling height, proportions, the view from the stage: exactly what sells a venue does not come across in photos.' },
      { title: 'Decisions are made by comparison', description: 'Anyone reviewing several venues decides by gut feeling from the first online impression. Without a VR tour, that impression stays thin.' },
    ],
    stats: [
      { value: '+40%', label: 'more leads with a virtual showroom tour' },
      { value: '+30%', label: 'higher online interaction with a 360° showroom' },
      { value: '2×', label: 'more interest in Google listings with a VR tour' },
      { value: '24/7', label: 'viewings possible – even on Sundays at 10 pm' },
    ],
    sources: [
      { label: 'Travvir: virtual tours generate around 40% more leads than photos alone (automotive)', url: 'https://travvir.com/blog/en/virtual-tour-car-dealerships' },
      { label: 'Spyne: +30% customer interaction with 3D/360° showroom tours', url: 'https://www.spyne.ai/blogs/3d-virtual-tours-for-car-dealerships' },
      { label: 'Google/Ipsos “Impact of Search Listings”: 2× more interest with a virtual tour (CloudPano)', url: 'https://www.cloudpano.com/blog/how-google-street-view-tours-increase-foot-traffic-to-local-businesses' },
    ],
    captures: ['Halls & event spaces', 'Foyer & reception', 'Stage & technology', 'Terraces & outdoor areas', 'Showroom & exhibition spaces', 'Access & parking'],
    extraSection: {
      title: 'Variants and documents directly in the VR tour',
      description: 'A venue sells through its possibilities. The VR tour shows them all – in one place.',
      items: [
        'Seating variants (banquet, concert, seminar) as switchable panoramas',
        'Technical data sheets, plans and catering documents as PDF downloads in the VR tour',
        'Enquiry hotspot right in the hall – interest becomes a concrete enquiry',
        'Seasonal updates (wedding decoration, Christmas atmosphere) possible at any time',
        'Shareable link for offers, e-mails and social media',
      ],
    },
    roiTitle: 'One booked event pays for your VR tour',
    roiSteps: [
      { label: 'Investment (event venue package)', value: 'from CHF 2\'990.– one-time' },
      { label: 'Revenue per event (wedding, function)', value: 'several thousand CHF' },
      { label: 'Break-even', value: '1 additional booking' },
    ],
    roiResult: 'Every further booking is profit – plus the wasted viewings you save.',
    comparisonTitle: 'Venue with vs without Signature Tour',
    comparisonKicker: 'The difference',
    comparisonWithoutHead: 'Photos & floor plan only',
    comparisonRows: [
      { label: 'Viewings', without: 'Many wasted appointments', with: 'Pre-qualified – only serious enquiries' },
      { label: 'Spatial impact', without: 'Photos do not show proportions', with: 'Hall & stage truly tangible' },
      { label: 'Variants', without: 'One standard image', with: 'Banquet, concert, seminar switchable' },
      { label: 'Documents', without: 'Sending separate PDFs', with: 'Technology & catering directly in the VR tour' },
      { label: 'Availability', without: 'By appointment only', with: 'Walkable 24/7' },
      { label: 'Image quality', without: 'Snapshots', with: 'Professional shots, clean floor (nadir)' },
    ],
    packageName: 'Event venue package',
    packagePrice: 'from CHF 2\'990.–',
    packageFeatures: [
      'Signature Tour of the complete venue incl. outdoor areas',
      'Day/night mode and video hotspots',
      'Enquiry hotspots and PDF integration (technology, catering, plans)',
      'Google Business integration & website embedding',
      'Incl. 12 months of Signature Care (care service)',
      'Large halls: Pro line from CHF 4\'497.–',
      'Seasonal update optional (CHF 180.– per scene / season pack CHF 650.–)',
    ],
    faqs: [
      { question: 'Can we show different seating arrangements?', answer: 'Yes. We shoot the hall in several variants (e.g. banquet and concert) – visitors switch between the views inside the VR tour.' },
      { question: 'What happens after a conversion or new decoration?', answer: 'Individual panoramas can be updated from CHF 180.– per scene without recreating the VR tour. Ideal for seasonal moods too.' },
      { question: 'Can event planners embed the VR tour in their documents?', answer: 'Yes. The virtual tour can be shared via link and embedded via iFrame – perfect for offers, pitch decks and partner websites.' },
      { question: 'How long does the shoot take?', answer: 'Depending on size, 2–4 hours, ideally when the venue is set up and empty. We deliver the finished tour in 5–10 working days.' },
    ],
  },
}
