import type { BranchenPageData } from './branchen-data'

// Französische Inhalte der Branchenseiten. Struktur identisch zu branchen-data.ts.
export const BRANCHEN_DATA_FR: Record<string, BranchenPageData> = {
  hotel: {
    slug: 'hotel',
    metaTitle: 'Visite 360° pour hôtels – plus de réservations directes',
    metaDescription: 'Plus de réservations directes, moins de commissions OTA : visites 360° professionnelles pour hôtels dès CHF 3\'490. Prestataire suisse – la visite vous appartient, pas d\'abonnement.',
    badge: 'Hôtels & resorts',
    headline: 'Visite 360° pour votre hôtel',
    tagline: 'Plus de réservations directes, moins de dépendance aux OTA. Montrez chambres, spa, restaurant et lobby à vos hôtes – avant qu’ils réservent.',
    heroImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1900&q=80&auto=format&fit=crop',
    challenges: [
      { title: 'Les coûts OTA rongent la marge', description: 'CHF 30\'000–100\'000 par an pour les hôtels. 15–18% de commission par réservation à Booking.com & Co.' },
      { title: '« Bien plus beau que sur les photos ! »', description: '90% des hôtes le disent. Mais en ligne ? Seulement des photos statiques qui ne transmettent pas l’atmosphère.' },
      { title: 'Les hôtes repartent réserver sur Booking', description: 'Votre site montre des photos statiques, l’hôte hésite et retourne réserver sur l’OTA – 15–18% de commission.' },
    ],
    stats: [
      { value: '+48%', label: 'de réservations directes en plus' },
      { value: '130%', label: 'de probabilité de réservation en plus (18–34 ans)' },
      { value: '3×', label: 'plus de temps passé sur votre site' },
      { value: '2×', label: 'plus de consultations du profil Google' },
    ],
    statsNote: 'Sources : données Google Street View Business, Matterport Insights, études sectorielles Hospitality',
    sources: [
      { label: 'Étude Omni Hotels : 67% de probabilité de réservation en plus avec visite 360° (EXP360)', url: 'https://exp360.com/blog/how-hotels-use-vr-360-images-and-videos-to-increase-bookings/' },
      { label: 'Visiting Media : comment les visites virtuelles augmentent les réservations hôtelières', url: 'https://visitingmedia.com/5-ways-virtual-tours-help-hotels-increase-bookings/' },
      { label: 'ScienceDirect : AR/VR dans l’hôtellerie – effet sur la satisfaction et l’intention de réservation', url: 'https://www.sciencedirect.com/science/article/pii/S0278431923002050' },
    ],
    captures: ['Types de chambres (simple, double, suite)', 'Lobby & réception', 'Restaurant', 'Spa & wellness', 'Espaces événementiels', 'Extérieurs'],
    comparisonTitle: 'Hôtel avec vs sans Signature Tour',
    comparisonKicker: 'La différence',
    comparisonWithoutHead: 'Sans visite 360°',
    comparisonWithoutSub: 'seulement des photos sur le site',
    comparisonRows: [
      { label: 'Temps passé', without: '1–2 minutes, puis l’hôte s’en va', with: '5–8 minutes dans l’expérience' },
      { label: 'Réservations directes', without: 'L’hôte retourne sur Booking & Co.', with: '+48% de réservations directes' },
      { label: 'Confiance des hôtes', without: 'Faible – photos statiques uniquement', with: 'Élevée – chambres & spa visitables à l’avance' },
      { label: 'Commissions OTA', without: '15–18% par réservation', with: 'Nettement réduites' },
      { label: 'Visibilité Google', without: 'Fiche standard', with: 'Placement privilégié avec visite' },
      { label: 'Qualité d’image', without: 'Instantanés au smartphone', with: 'Prises de vue pro, sol propre (nadir)' },
    ],
    roiTitle: '10 réservations directes suffisent à payer votre visite',
    roiSteps: [
      { label: 'Prix moyen d’une chambre', value: 'CHF 200 / nuit' },
      { label: 'Commission OTA économisée (18%)', value: 'CHF 36 / nuit' },
      { label: '10 réservations directes de 2 nuits', value: 'CHF 720 économisés' },
    ],
    roiResult: 'La visite s’amortit souvent dès le premier trimestre.',
    packageName: 'Forfait hôtel',
    packagePrice: 'dès CHF 3\'490.–',
    packageFeatures: [
      'Tous les types de chambres, lobby, restaurant, spa, extérieurs',
      'Points de réservation & navigation par plan',
      'Multilinguisme (DE / FR / EN)',
      'Intégration Google Business',
      'Incl. 12 mois de Signature Evolution (service de suivi)',
      'Grands établissements, thermes & resorts : ligne Pro dès CHF 4\'497.–',
    ],
    faqs: [
      { question: 'Combien de temps dure la prise de vue ?', answer: '4–6 heures selon la taille de l’hôtel. Nous planifions le rendez-vous après le check-out / avant le check-in.' },
      { question: 'Et si nous rénovons des chambres ?', answer: 'Selon le forfait de service, les mises à jour de panoramas sont déjà incluses – ou à l’unité dès CHF 180.– par scène. Pas besoin d’une nouvelle prise de vue complète.' },
      { question: 'La visite peut-elle renvoyer vers notre système de réservation ?', answer: 'Oui. Les hôtes peuvent réserver directement depuis la visite le type de chambre qu’ils sont en train de regarder.' },
      { question: 'La visite fonctionne-t-elle aussi sur smartphone ?', answer: 'Oui, entièrement responsive. Aucune application nécessaire. Les casques VR sont également pris en charge.' },
    ],
  },

  restaurant: {
    slug: 'restaurant',
    metaTitle: 'Visite 360° pour restaurants',
    metaDescription: '93% des clients cherchent sur Google avant de choisir un restaurant. Montrez votre ambiance avec une visite 360° professionnelle.',
    badge: 'Gastronomie',
    headline: 'Visite 360° pour votre restaurant',
    tagline: '93% des clients cherchent sur Google avant de choisir un restaurant. Montrez votre ambiance – pas seulement votre carte.',
    heroImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1900&q=80&auto=format&fit=crop',
    challenges: [
      { title: 'Photos Google incontrôlées', description: 'Les clients publient des photos floues et mal éclairées qui façonnent la première impression.' },
      { title: 'Invisibilité en ligne', description: 'Sans contenu visuel, vous perdez dans les résultats de recherche. La concurrence gagne.' },
      { title: 'Journées de 14 heures = pas de marketing', description: 'Pas de temps pour créer du contenu professionnel en plus du quotidien.' },
    ],
    stats: [
      { value: '+85%', label: 'de réservations en plus grâce aux visites virtuelles' },
      { value: '+50%', label: 'de visites du site web en plus' },
      { value: '2×', label: 'plus de consultations sur Google Maps' },
      { value: '93%', label: 'cherchent sur Google avant de choisir' },
    ],
    statsNote: 'Sources : données Google Street View Business, études sectorielles gastronomie',
    sources: [
      { label: 'Google/Ipsos « Impact of Search Listings » : les fiches avec visite virtuelle suscitent deux fois plus d’intérêt (CloudPano)', url: 'https://www.cloudpano.com/blog/how-google-street-view-tours-increase-foot-traffic-to-local-businesses' },
      { label: 'Panoee : comment Google Street View augmente la fréquentation', url: 'https://panoee.com/why-google-street-view-can-boost-traffic-to-your-store/' },
    ],
    captures: ['Salle', 'Terrasse & extérieurs', 'Bar & lounge', 'Salons privés & événements', 'Cuisine (en option) – transparence qui crée la confiance'],
    roiTitle: 'Moins d’un espresso par jour',
    roiSteps: [
      { label: 'Investissement (forfait gastro)', value: 'dès CHF 2\'890.– une fois' },
      { label: 'Calculé sur 3 ans', value: 'env. CHF 2.65 / jour' },
      { label: '1 réservation de plus par semaine (CHF 45 p.p.)', value: '> CHF 7\'000 / an' },
    ],
    roiResult: 'Deux réservations supplémentaires par semaine suffisent à payer toute la visite.',
    extraSection: {
      title: 'Intégration Google Business',
      description: 'Votre visite 360° est intégrée directement à votre profil Google Business. Des prises de vue professionnelles remplacent les photos incontrôlées des clients.',
      items: [
        'Visite directement dans le profil Google Business',
        'Taux de clics plus élevé sur Google Maps',
        'Plus d’appels, plus de réservations',
        'Avantage concurrentiel vs restaurants sans visite',
      ],
    },
    comparisonTitle: 'Restaurant avec vs sans Signature Tour',
    comparisonKicker: 'La différence',
    comparisonWithoutHead: 'Photos & carte uniquement',
    comparisonRows: [
      { label: 'Première impression en ligne', without: 'Photos floues de clients sur Google', with: 'Ambiance professionnelle que vous maîtrisez' },
      { label: 'Réservations', without: 'Le client hésite et continue sa recherche', with: 'L’ambiance convainc avant la réservation' },
      { label: 'Google Maps', without: 'Fiche standard', with: 'Visite dans le profil – plus de clics & appels' },
      { label: 'Effort', without: 'Pas de marketing en plus du quotidien', with: 'Créée une fois, travaille des années' },
      { label: 'Actualité', without: 'Les photos vieillissent', with: 'Mises à jour saisonnières possibles' },
      { label: 'Qualité d’image', without: 'Instantanés au smartphone', with: 'Prises de vue pro, sol propre (nadir)' },
    ],
    packageName: 'Forfait gastro',
    packagePrice: 'dès CHF 2\'890.–',
    packageFeatures: [
      'Signature Tour avec intégration Google Business',
      'Mode jour/nuit pour l’ambiance de jour et de soir',
      'Pack QR codes pour table et vitrine',
      '1 mise à jour saisonnière incluse (déco de fêtes, tables d’été)',
      'Incl. 12 mois de Signature Care (service de suivi)',
      'Petits établissements : Basic Tour dès CHF 990.–',
    ],
    faqs: [
      { question: 'Devons-nous fermer pendant la prise de vue ?', answer: 'Non, nous photographions avant l’ouverture ou pendant une période calme. 60–90 minutes suffisent généralement.' },
      { question: 'Peut-on adapter la visite selon les saisons ?', answer: 'Oui, 1 mise à jour saisonnière est incluse. D’autres peuvent être ajoutées à tout moment.' },
      { question: 'Qu’advient-il des anciennes photos Google de nos clients ?', answer: 'La visite professionnelle apparaît en bonne place. Les photos des clients restent, mais votre visite domine la première impression visuelle.' },
    ],
  },

  'spa-wellness': {
    slug: 'spa-wellness',
    metaTitle: 'Visite 360° pour spa & wellness',
    metaDescription: 'Rendez votre atmosphère de bien-être accessible en ligne. Visites 360° professionnelles pour espaces spa.',
    badge: 'Spa & wellness',
    headline: 'Faites vivre votre atmosphère de bien-être',
    tagline: 'Les hôtes disent : « C’est encore plus beau que sur les photos. » Faites-leur ressentir l’atmosphère déjà en ligne.',
    heroImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1900&q=80&auto=format&fit=crop',
    demoTour: { url: 'https://vtour.cloud/e16tqj/ee82pes6/#node69', title: 'AQUAVIRAT – Spa & bains', note: 'Une vraie Signature Tour : piscine, espace saunas et zones de repos – avec réservation directement dans la visite.' },
    challenges: [
      { title: 'Une atmosphère intransmissible', description: 'Les photos montrent des pièces, pas la sensation : chaleur du sauna, silence des zones de repos, ampleur des lieux.' },
      { title: 'Un déficit de conversion', description: 'Les visiteurs sont intéressés mais ne réservent pas. Il manque l’expérience décisive qui crée la confiance.' },
      { title: 'Pression concurrentielle', description: 'Les grandes chaînes wellness investissent dans le marketing vidéo. La différenciation doit être authentique.' },
    ],
    stats: [
      { value: '+45%', label: 'de réservations en plus après une visite virtuelle' },
      { value: '67%', label: 'de probabilité de réservation en plus chez les visiteurs de la visite' },
      { value: '4–5×', label: 'plus de temps passé sur les pages avec visite 360°' },
      { value: '15–25%', label: 'd’adoption dans l’espace DACH – votre avance, maintenant' },
    ],
    statsNote: 'Sources : Matterport Insights, études sectorielles wellness & hospitality',
    sources: [
      { label: 'EXP360 : contenus 360° dans l’hôtellerie et le wellness', url: 'https://exp360.com/blog/how-hotels-use-vr-360-images-and-videos-to-increase-bookings/' },
      { label: 'ScienceDirect : visites virtuelles et satisfaction client – quasi-expérience (Airbnb)', url: 'https://www.sciencedirect.com/science/article/abs/pii/S1447677025000105' },
    ],
    captures: ['Espace saunas', 'Salles de soins', 'Zones de repos', 'Piscines & jacuzzis', 'Extérieurs', 'Jardin / bassin naturel / vue panoramique'],
    extraSection: {
      title: 'Sphère privée & discrétion',
      description: 'Vos hôtes restent protégés. Nous garantissons une discrétion absolue à chaque prise de vue.',
      items: [
        'Prise de vue en dehors des heures d’ouverture – aucun hôte sur les images',
        'Conforme au RGPD : aucune personne, aucun détail identifiable',
        'Post-production professionnelle avec contrôle qualité',
        'Vous validez chaque image avant publication',
        'En option : exclure certaines zones',
      ],
    },
    comparisonTitle: 'Spa avec vs sans Signature Tour',
    comparisonKicker: 'La différence',
    comparisonWithoutHead: 'Photos uniquement',
    comparisonRows: [
      { label: 'Atmosphère', without: 'Les photos montrent des pièces, pas la sensation', with: 'Calme & haut de gamme perceptibles' },
      { label: 'Réservations', without: 'L’intéressé hésite', with: 'L’expérience crée la confiance → réservation' },
      { label: 'Discrétion', without: 'Photos de clients incontrôlées', with: 'Prises de vue sans hôtes, validation préalable' },
      { label: 'Différenciation', without: 'Comme tous les autres', with: 'Avance visible sur les chaînes' },
      { label: 'Visibilité Google', without: 'Fiche standard', with: 'Visite dans le profil' },
      { label: 'Qualité d’image', without: 'Instantanés', with: 'Prises de vue pro, sol propre (nadir)' },
    ],
    packageName: 'Visite premium spa & wellness',
    packagePrice: 'dès CHF 3\'490.–',
    packageFeatures: [
      'Signature Tour de tout l’espace spa',
      'Audioguide & mode jour/nuit pour une atmosphère palpable',
      'Prise de vue hors heures d’ouverture, conforme au RGPD',
      'Intégration Google Business & intégration au site web',
      'Incl. 12 mois de Signature Care (service de suivi)',
      'En option : terrasse quatre saisons – CHF 1\'490.– / an',
    ],
    faqs: [
      { question: 'Comment garantissez-vous qu’aucun hôte n’apparaît sur les images ?', answer: 'Prise de vue exclusive en dehors des heures d’exploitation, dans un créneau convenu à l’avance. L’espace spa est fermé aux hôtes.' },
      { question: 'Pouvons-nous exclure certaines zones ?', answer: 'Oui, vous décidez de ce qui est montré. Locaux techniques, zones du personnel, etc. peuvent être exclus.' },
      { question: 'Combien de temps dure la prise de vue d’un spa complet ?', answer: '2–4 heures selon la taille. Les grands espaces avec intérieur et extérieur peuvent nécessiter une demi-journée. Livraison en 5–7 jours.' },
    ],
  },

  fitnessstudio: {
    slug: 'fitnessstudio',
    metaTitle: 'Visite 360° pour salles de fitness',
    metaDescription: 'Abaissez le seuil d’entrée des nouveaux visiteurs. 130% de probabilité de visite en plus avec une visite 360°.',
    badge: 'Fitness & sport',
    headline: 'Vivre votre salle – avant même le premier pas',
    tagline: '82% se renseignent en ligne. Abaissez le seuil d’entrée des nouveaux visiteurs.',
    heroImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1900&q=80&auto=format&fit=crop',
    challenges: [
      { title: '« Il faut le vivre »', description: 'Impossible de juger la qualité sans visite. Seuil d’entrée élevé pour les nouveaux.' },
      { title: '20% de rotation annuelle', description: 'Le secteur lutte contre une forte rotation. Les membres qui savent à quoi s’attendre restent plus longtemps.' },
      { title: 'Les chaînes discount dominent', description: 'McFit, FitX dominent la recherche avec de gros budgets marketing. Différenciez-vous en ligne comme salle de qualité.' },
    ],
    stats: [
      { value: '130%', label: 'de probabilité de visite en plus avec fiche Google avec visite' },
      { value: '2×', label: 'plus de consultations Google Maps vs fiches sans visite' },
      { value: 'EUR 960', label: 'de lifetime value moyenne par membre (24 mois × €40)' },
    ],
    statsNote: 'Sources : données Google Street View Business, études sectorielles fitness',
    sources: [
      { label: 'Google/Ipsos « Impact of Search Listings » : deux fois plus d’intérêt avec visite virtuelle (CloudPano)', url: 'https://www.cloudpano.com/blog/how-google-street-view-tours-increase-foot-traffic-to-local-businesses' },
      { label: 'TeliportMe : analyse du marché des logiciels de visite virtuelle 2024', url: 'https://teliportme.com/blog/a-deep-dive-into-the-virtual-tour-software-market/' },
    ],
    captures: ['Surface d’entraînement', 'Espace poids libres', 'Espace cardio', 'Salle(s) de cours', 'Wellness & sauna (le cas échéant)', 'Vestiaires & douches'],
    extraSection: {
      title: 'La qualité plutôt que le prix',
      description: 'Les chaînes discount gagnent par le prix – gagnez par la qualité. Mais seulement si elle est visible en ligne.',
      items: [
        'Équipements haut de gamme vs traitement de masse',
        'Atmosphère personnelle vs exploitation anonyme',
        'Vestiaires propres et modernes',
        'Salles de cours, espaces wellness, extras justifient le prix premium',
        'La sensation « je veux m’entraîner ici » avant l’essai',
      ],
    },
    roiTitle: '3 nouveaux membres paient votre visite',
    roiSteps: [
      { label: 'Valeur par membre (24 mois × CHF 40)', value: 'env. CHF 960' },
      { label: 'Investissement (forfait fitness)', value: 'dès CHF 2\'890.– une fois' },
      { label: 'Break-even', value: '3 nouveaux membres' },
    ],
    roiResult: 'Agit pendant 3 ans – sans frais publicitaires récurrents, sans dispersion.',
    comparisonTitle: 'Salle avec vs sans Signature Tour',
    comparisonKicker: 'La différence',
    comparisonWithoutHead: 'Photos uniquement',
    comparisonRows: [
      { label: 'Seuil d’entrée', without: 'Le nouveau hésite et ne vient pas', with: 'Salle visitable à l’avance → essai' },
      { label: 'Différenciation', without: 'Noyé face aux discounters', with: 'Qualité rendue visible' },
      { label: 'Fidélisation', without: 'Fausses attentes, résiliation rapide', with: 'Qui sait à quoi s’attendre reste plus longtemps' },
      { label: 'Google Maps', without: 'Fiche standard', with: 'Visite dans le profil – plus de consultations' },
      { label: 'Réseaux sociaux', without: 'Pas de contenu partageable', with: 'Lien partageable pour Instagram & Co.' },
      { label: 'Qualité d’image', without: 'Instantanés', with: 'Prises de vue pro, sol propre (nadir)' },
    ],
    packageName: 'Forfait fitness',
    packagePrice: 'dès CHF 2\'890.–',
    packageFeatures: [
      'Signature Tour de toute la salle',
      'Formulaire de capture de leads (« demander un essai »)',
      'Intégration Google Business & intégration au site web',
      'Optimisé pour mobile, ordinateur, TV et casque VR',
      'Incl. 12 mois de Signature Care (service de suivi)',
      'Livraison en 5–7 jours ouvrables',
    ],
    faqs: [
      { question: 'Des membres apparaissent-ils pendant la prise de vue ?', answer: 'Non, nous photographions en dehors des heures de pointe ou avant l’ouverture. La salle est montrée vide et rangée – c’est toujours ainsi qu’elle paraît le mieux.' },
      { question: 'Notre salle n’est pas très grande. Est-ce quand même rentable ?', answer: 'Oui. Les salles compactes et bien équipées sont impressionnantes en 360°. L’effet d’espace est pleinement mis en valeur.' },
      { question: 'Pouvons-nous utiliser la visite sur les réseaux sociaux ?', answer: 'Oui, lien partageable pour Instagram, Facebook, newsletter, portails d’avis. Aucun téléchargement d’application nécessaire.' },
    ],
  },

  immobilien: {
    slug: 'immobilien',
    metaTitle: 'Visites 360° professionnelles pour l’immobilier',
    metaDescription: 'Moins de visites inutiles, des intéressés plus qualifiés. Visites 360° sans contrat de longue durée.',
    badge: 'Immobilier & courtiers',
    headline: 'Des visites 360° professionnelles pour vos objets',
    tagline: 'Moins de tourisme de visite, des intéressés plus qualifiés. Sans contrat de longue durée.',
    heroImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1900&q=80&auto=format&fit=crop',
    demoTour: { url: 'https://vtour.cloud/e16tqj/cltkwbjc/', title: 'Luxury Apartment – Widen', note: 'Une vraie Signature Tour d’un appartement premium : séjour, cuisine, salle de bains et extérieurs visitables 24 h/24.' },
    challenges: [
      { title: 'Le tourisme de visite', description: 'Traverser la ville, ouvrir, présenter. Après 5 minutes, l’intéressé dit : « Ce n’est pas ce que j’imaginais. »' },
      { title: 'La concurrence des grands courtiers', description: 'Engel & Völkers utilisent déjà visites virtuelles et visualisations. Sans présence comparable, vous perdez des mandats.' },
      { title: 'Les attentes des propriétaires', description: 'Les propriétaires attendent un marketing professionnel. Des photos standard ? Le mandat ira au courtier avec le meilleur concept.' },
    ],
    stats: [
      { value: '+40%', label: 'de clics en plus sur les annonces avec visite virtuelle' },
      { value: '+95%', label: 'de taux de contact en plus sur les annonces avec visite 360°' },
      { value: '5×', label: 'vente plus rapide grâce à des intéressés préqualifiés' },
      { value: '3×', label: 'plus de temps passé sur l’annonce' },
    ],
    statsNote: 'Sources : Matterport Insights, National Association of Realtors (NAR)',
    sources: [
      { label: 'Étude Matterport : acheteurs et vendeurs préfèrent nettement les annonces avec visite 3D', url: 'https://matterport.com/news/new-study-shows-property-buyers-and-sellers-overwhelmingly-prefer-listings-3d-tours' },
      { label: 'Matterport : les objets avec visite 3D se vendent jusqu’à 31% plus vite', url: 'https://matterport.com/blog/3d-tours-properties-sell-31-faster-and-higher-price' },
      { label: 'NAR : Home Buyers & Sellers Generational Trends Report', url: 'https://www.nar.realtor/research-and-statistics/research-reports/home-buyer-and-seller-generational-trends' },
    ],
    captures: ['Pièces à vivre', 'Cuisine', 'Salles de bains', 'Extérieurs', 'Intégration du plan (en option)'],
    comparisonTitle: 'Pourquoi les courtiers passent à Signatour',
    comparisonKicker: 'La comparaison honnête',
    comparisonWithoutHead: 'Prestataires habituels',
    comparisonWithoutSub: 'Ogulo, Matterport',
    comparisonRows: [
      { label: 'Prix par objet', without: 'Frais mensuels + setup, à durée illimitée', with: 'dès CHF 1\'623.– par objet (carte 10) – puis elle vous appartient' },
      { label: 'Engagement contractuel', without: '12–24 mois de durée minimale', with: 'Aucun – carte avantage sans date d’expiration' },
      { label: 'Votre effort', without: 'Scanner soi-même, apprendre le logiciel (DIY)', with: 'Zéro – nous venons, photographions, livrons' },
      { label: 'Qualité d’image', without: 'Dépend de vos propres photos', with: 'Photographe pro, sol propre (nadir 95–100%)' },
      { label: 'Google & portails', without: 'Non inclus', with: 'Google Business, Homegate & ImmoScout inclus' },
      { label: 'Souveraineté des données', without: 'Cloud du prestataire, résiliation = perte des données', with: 'Chez vous – pas de verrouillage' },
    ],
    extraSection: {
      title: 'Compatibilité avec les portails',
      description: 'Nos visites 360° fonctionnent sur tous les grands portails immobiliers.',
      items: [
        'Homegate – visite virtuelle directement dans l’annonce',
        'ImmoScout24.ch – visibilité maximale grâce à l’intégration de la visite',
        'flatfox – présentation moderne pour la recherche locative numérique',
        'newhome – présence professionnelle sur la place de marché suisse',
        'Votre propre site – intégration simple par iFrame ou lien',
      ],
    },
    roiTitle: 'Un seul mandat gagné paie toute la carte',
    roiSteps: [
      { label: 'Visite par objet (carte 10)', value: 'CHF 1\'623.–' },
      { label: 'Clics en plus sur les annonces', value: '+40%' },
      { label: 'Taux de contact plus élevé', value: '+95%' },
    ],
    roiResult: 'Un seul mandat gagné paie la carte complète – pour les objets de luxe, la commission atteint cinq chiffres.',
    packageName: 'Cartes avantage Signature',
    packagePrice: 'CHF 2\'497.– par objet',
    packageFeatures: [
      'Objet individuel : CHF 2\'497.– par objet',
      'Carte avantage 5 : CHF 9\'990.– (CHF 1\'998.– par objet, env. 20% d’avantage)',
      'Carte avantage 10 : CHF 16\'230.– (CHF 1\'623.– par objet, 35% d’avantage)',
      'Chaque visite en qualité Signature, entièrement à votre charte graphique',
      'Utilisation flexible, sans date d’expiration',
      'Intégration Google & portails par objet',
      'Incl. 12 mois de service de suivi par visite',
    ],
    faqs: [
      { question: 'Quand la visite est-elle disponible après la prise de vue ?', answer: 'En règle générale 5–10 jours ouvrables. En urgence : livraison express en 3 jours ouvrables (+30%).' },
      { question: 'Que se passe-t-il une fois l’objet vendu ou loué ?', answer: 'La visite est désactivée/supprimée. Utilisez la visite suivante de la carte pour un nouvel objet. Pas de date d’expiration.' },
      { question: 'Le bien doit-il être vide pour la prise de vue ?', answer: 'Non. Les objets meublés paraissent souvent plus attrayants en 360°. On s’y projette mieux. Nous vous conseillons sur la préparation optimale.' },
    ],
  },

  'banken-versicherungen': {
    slug: 'banken-versicherungen',
    metaTitle: 'Visite 360° pour banques, assurances & études',
    metaDescription: 'La confiance commence avant le premier rendez-vous : visites 360° discrètes pour banques, assurances et études. Prestataire suisse, conforme au RGPD.',
    badge: 'Banques, assurances & études',
    headline: 'La confiance naît avant le premier rendez-vous',
    tagline: 'Dans les services financiers et juridiques, la première impression décide de la demande de mandat. Montrez professionnalisme et discrétion – avant même le premier entretien.',
    heroImage: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1900&q=80&auto=format&fit=crop',
    challenges: [
      { title: 'Seuil élevé avant le premier entretien', description: 'Qui confie fortune, assurance ou dossier juridique veut savoir à qui il s’adresse. Un site anonyme n’abaisse pas ce seuil.' },
      { title: 'Des sites interchangeables', description: 'Photos de stock et textes standard dominent le secteur. Qui montre ses propres locaux prouve sa substance là où d’autres se contentent d’affirmer.' },
      { title: 'Des locaux premium invisibles', description: 'Vous avez investi dans des espaces d’accueil et de conseil représentatifs – en ligne, personne ne les voit avant le rendez-vous.' },
    ],
    stats: [
      { value: '49%', label: 'des mandants évaluent une étude en ligne avant d’appeler' },
      { value: '94%', label: 'de crédibilité perçue en plus avec une présence en ligne complète' },
      { value: '2×', label: 'plus d’intérêt pour les fiches avec visite virtuelle' },
      { value: '24/7', label: 'votre accueil numérique est toujours ouvert' },
    ],
    sources: [
      { label: 'Digital Roots Media : 49% évaluent l’étude via le site avant d’appeler', url: 'https://www.digitalrootsmedia.com/blog/legal/law-firm-web-design-convert-visitors-clients/' },
      { label: 'Google/Ipsos « Impact of Search Listings » : 94% de sérieux perçu en plus, 2× plus d’intérêt avec visite virtuelle (CloudPano)', url: 'https://www.cloudpano.com/blog/how-google-street-view-tours-increase-foot-traffic-to-local-businesses' },
      { label: 'Panoee : effet des contenus Street View sur les entreprises locales', url: 'https://panoee.com/why-google-street-view-can-boost-traffic-to-your-store/' },
    ],
    captures: ['Accueil & lobby', 'Salles de conseil', 'Salles de réunion', 'Hall des guichets (banques)', 'Bibliothèque & espaces de travail (études)', 'Présence extérieure & accès'],
    extraSection: {
      title: 'Discrétion & sécurité',
      description: 'Nous connaissons les exigences des secteurs sensibles – chaque prise de vue suit un processus de validation clair.',
      items: [
        'Prise de vue en dehors des heures d’ouverture – aucun client, aucun collaborateur à l’image',
        'Aucun document, écran ou détail sensible sur les prises de vue',
        'Vous validez chaque panorama avant publication',
        'Les zones critiques pour la sécurité sont exclues',
        'Hébergement conforme au RGPD en Suisse/UE, contrat de sous-traitance inclus',
      ],
    },
    comparisonTitle: 'Avec vs sans Signature Tour',
    comparisonKicker: 'La différence',
    comparisonWithoutHead: 'Site & photos de stock uniquement',
    comparisonRows: [
      { label: 'Première impression', without: 'Photos de stock anonymes', with: 'Vos vrais locaux – confiance immédiate' },
      { label: 'Seuil d’entrée', without: 'Élevé avant le premier entretien', with: 'Abaissé – le mandant vous connaît déjà' },
      { label: 'Discrétion', without: 'Aucun contrôle', with: 'Sans personnes/documents, processus de validation' },
      { label: 'Différenciation', without: 'Présence interchangeable', with: 'Professionnalisme visible' },
      { label: 'Disponibilité', without: 'Aux heures de bureau uniquement', with: 'Accueil numérique 24 h/24' },
      { label: 'Qualité d’image', without: 'Matériel de stock', with: 'Prises de vue pro, sol propre (nadir)' },
    ],
    packageName: 'Tarif par succursale',
    packagePrice: 'dès CHF 2\'497.– par site',
    packageFeatures: [
      '1 site : CHF 2\'497.–',
      '3–4 sites : CHF 2\'247.– par site (10%)',
      '5–9 sites : CHF 1\'873.– par site (25%)',
      'dès 10 sites : CHF 1\'623.– par site (35%)',
      'Signature Tour à votre charte graphique, un interlocuteur pour tous les sites',
      'Processus de validation discret avant publication',
      'Recommandé avec forfait de service par site',
    ],
    faqs: [
      { question: 'Comment garantissez-vous la discrétion ?', answer: 'Nous photographions en dehors des heures d’ouverture, sans personnes, documents ni contenus d’écran. Chaque panorama passe par votre processus de validation avant d’être mis en ligne. Les zones sensibles restent exclues.' },
      { question: 'Combien de temps dure la prise de vue ?', answer: 'Pour l’accueil, les salles de conseil et de réunion, en général 1–2 heures – planifiable le soir ou le week-end, sans interruption d’exploitation.' },
      { question: 'Est-ce rentable pour une petite étude ?', answer: 'Justement : les mandants comparent en ligne avant de demander. La seule étude de la place qui montre ses locaux se distingue visiblement – la visite travaille des années sans frais récurrents.' },
      { question: 'Est-ce possible aussi en allemand ou en anglais ?', answer: 'Oui. Conseil & mandats en allemand, français et anglais – et la visite elle-même peut être réalisée en plusieurs langues (dès CHF 300 par langue supplémentaire).' },
    ],
  },

  eventlocations: {
    slug: 'eventlocations',
    metaTitle: 'Visite 360° pour lieux d’événements & showrooms',
    metaDescription: 'Futurs mariés et organisateurs comparent en ligne : visites 360° pour lieux d’événements, salles et showrooms. Moins de visites à vide, plus de demandes qualifiées.',
    badge: 'Lieux d’événements & showrooms',
    headline: 'Votre lieu convainc – avant même la demande',
    tagline: 'Futurs mariés, organisateurs et acheteurs comparent en ligne. Qui rend salle, scène et ambiance accessibles reçoit la demande qualifiée – la concurrence, seulement le clic suivant.',
    heroImage: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=1900&q=80&auto=format&fit=crop',
    challenges: [
      { title: 'Chaque visite coûte des heures', description: 'Coordonner le rendez-vous, préparer le lieu, faire la visite – et l’intéressé constate après 10 minutes que la salle est trop petite.' },
      { title: 'Les photos ne montrent pas l’effet d’espace', description: 'Hauteur sous plafond, proportions, vue depuis la scène : exactement ce qui vend un lieu ne passe pas sur les photos.' },
      { title: 'Les décisions se prennent en comparant', description: 'Qui examine plusieurs lieux décide à l’instinct sur la première impression en ligne. Sans visite, cette impression reste mince.' },
    ],
    stats: [
      { value: '+40%', label: 'de leads en plus avec une visite virtuelle de showroom' },
      { value: '+30%', label: 'd’interaction en ligne en plus avec un showroom 360°' },
      { value: '2×', label: 'plus d’intérêt pour les fiches Google avec visite' },
      { value: '24/7', label: 'visite possible – même le dimanche à 22 h' },
    ],
    sources: [
      { label: 'Travvir : les visites virtuelles génèrent env. 40% de leads en plus que les photos seules (automobile)', url: 'https://travvir.com/blog/en/virtual-tour-car-dealerships' },
      { label: 'Spyne : +30% d’interaction client avec les visites showroom 3D/360°', url: 'https://www.spyne.ai/blogs/3d-virtual-tours-for-car-dealerships' },
      { label: 'Google/Ipsos « Impact of Search Listings » : 2× plus d’intérêt avec visite virtuelle (CloudPano)', url: 'https://www.cloudpano.com/blog/how-google-street-view-tours-increase-foot-traffic-to-local-businesses' },
    ],
    captures: ['Salles & surfaces événementielles', 'Foyer & accueil', 'Scène & technique', 'Terrasses & extérieurs', 'Surfaces de showroom & d’exposition', 'Accès & parking'],
    extraSection: {
      title: 'Variantes et documents directement dans la visite',
      description: 'Un lieu se vend par ses possibilités. La visite les montre toutes – au même endroit.',
      items: [
        'Variantes de disposition (banquet, concert, séminaire) en panoramas commutables',
        'Fiches techniques, plans et documents traiteur en PDF dans la visite',
        'Point de demande directement dans la salle – l’intérêt devient une demande concrète',
        'Mises à jour saisonnières (déco de mariage, ambiance de Noël) à tout moment',
        'Lien partageable pour offres, e-mails et réseaux sociaux',
      ],
    },
    roiTitle: 'Un seul événement réservé paie votre visite',
    roiSteps: [
      { label: 'Investissement (forfait lieu d’événements)', value: 'dès CHF 2\'990.– une fois' },
      { label: 'Chiffre d’affaires par événement (mariage, fête)', value: 'plusieurs milliers de CHF' },
      { label: 'Break-even', value: '1 conclusion supplémentaire' },
    ],
    roiResult: 'Chaque réservation supplémentaire est du bénéfice – plus les visites à vide économisées.',
    comparisonTitle: 'Lieu avec vs sans Signature Tour',
    comparisonKicker: 'La différence',
    comparisonWithoutHead: 'Photos & plan uniquement',
    comparisonRows: [
      { label: 'Visites', without: 'Beaucoup de rendez-vous à vide', with: 'Préqualifiées – seulement des demandes sérieuses' },
      { label: 'Effet d’espace', without: 'Les photos ne montrent pas les proportions', with: 'Salle & scène réellement perceptibles' },
      { label: 'Variantes', without: 'Une seule image standard', with: 'Banquet, concert, séminaire commutables' },
      { label: 'Documents', without: 'PDF envoyés séparément', with: 'Technique & traiteur directement dans la visite' },
      { label: 'Disponibilité', without: 'Sur rendez-vous uniquement', with: 'Visitable 24 h/24' },
      { label: 'Qualité d’image', without: 'Instantanés', with: 'Prises de vue pro, sol propre (nadir)' },
    ],
    packageName: 'Forfait lieu d’événements',
    packagePrice: 'dès CHF 2\'990.–',
    packageFeatures: [
      'Signature Tour du lieu complet, extérieurs inclus',
      'Mode jour/nuit et points vidéo',
      'Points de demande et intégration PDF (technique, traiteur, plans)',
      'Intégration Google Business & intégration au site web',
      'Incl. 12 mois de Signature Care (service de suivi)',
      'Grandes salles et halles : ligne Pro dès CHF 4\'497.–',
      'Mise à jour saisonnière en option (CHF 180.– par scène / pack saison CHF 650.–)',
    ],
    faqs: [
      { question: 'Pouvons-nous montrer différentes dispositions ?', answer: 'Oui. Nous photographions la salle en plusieurs variantes (p. ex. banquet et concert) – les visiteurs basculent entre les vues dans la visite.' },
      { question: 'Que se passe-t-il après une transformation ou une nouvelle déco ?', answer: 'Les panoramas individuels se mettent à jour dès CHF 180.– par scène, sans refaire la visite. Idéal aussi pour les ambiances saisonnières.' },
      { question: 'Les organisateurs peuvent-ils intégrer la visite à leurs documents ?', answer: 'Oui. La visite se partage par lien et s’intègre par iFrame – parfait pour les offres, les présentations et les sites partenaires.' },
      { question: 'Combien de temps dure la prise de vue ?', answer: 'Selon la taille, 2–4 heures, idéalement lorsque le lieu est aménagé et vide. Nous livrons la visite terminée en 5–10 jours ouvrables.' },
    ],
  },
}
